[workspace]
members = [
    "msim",
    "msim-macros",
    "msim-tokio",
    "mocked-crates/futures-timer",
]
exclude = [
    "tokio",
    "test-crates/jsonrpsee-test",
]

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(msim)',
] }
